version: '3.8'
services:
  postgres:
    image: postgres:16
    container_name: payments-db
    environment:
      POSTGRES_DB: payments
      POSTGRES_USER: payments_user
      POSTGRES_PASSWORD: payments_pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: